/**
 * Service URL configuration for production deployment.
 *
 * In development, Vite's proxy handles routing (all paths go to localhost).
 * In production, each microservice has its own API Gateway URL.
 *
 * Set these in frontend/.env.production (auto-generated by deploy.ps1):
 *   VITE_PROFILE_API_URL=https://xxx.execute-api.ap-south-1.amazonaws.com/v1
 *   VITE_LOAN_API_URL=https://yyy.execute-api.ap-south-1.amazonaws.com/v1
 *   etc.
 */

const SERVICE_URLS: Record<string, string> = {
  "/api/v1/auth":          import.meta.env.VITE_SECURITY_API_URL ?? "",
  "/api/v1/security":      import.meta.env.VITE_SECURITY_API_URL ?? "",
  "/api/v1/profiles":      import.meta.env.VITE_PROFILE_API_URL ?? "",
  "/api/v1/loans":         import.meta.env.VITE_LOAN_API_URL ?? "",
  "/api/v1/risk":          import.meta.env.VITE_RISK_API_URL ?? "",
  "/api/v1/cashflow":      import.meta.env.VITE_CASHFLOW_API_URL ?? "",
  "/api/v1/early-warning": import.meta.env.VITE_EARLY_WARNING_API_URL ?? "",
  "/api/v1/guidance":      import.meta.env.VITE_GUIDANCE_API_URL ?? "",
  "/api/v1/ai-advisor":    import.meta.env.VITE_AI_ADVISOR_API_URL ?? "",
};

/**
 * Resolve a relative API path to the correct full URL.
 *
 * - In development (VITE_*_URL not set): returns the path as-is (Vite proxy handles it).
 * - In production: prepends the correct service's API Gateway URL.
 *
 * Example:
 *   resolveUrl("/api/v1/profiles/123") → "https://xxx.execute-api.../v1/api/v1/profiles/123"
 */
export function resolveUrl(path: string): string {
  for (const [prefix, baseUrl] of Object.entries(SERVICE_URLS)) {
    if (path.startsWith(prefix) && baseUrl) {
      return `${baseUrl}${path}`;
    }
  }
  // Fallback: return as-is (works with Vite proxy in dev)
  return path;
}

/** Check if we're in production mode (service URLs configured). */
export const isProduction = Object.values(SERVICE_URLS).some((url) => url !== "");
